### ISSUE TITLE
Potential missing package

### ISSUE THREAD

**Issue by darrencl** [djsegal/julia_packages#186] opened 2020-11-13 05:16 UTC
Hi, I have registered a package for feature selection, named `FeatureSelector.jl`. It is already registered in the general registry [here](https://github.com/JuliaRegistries/General/tree/master/F/FeatureSelectors), but I could not find it in Julia package website. Am I missing anything here?

Thanks

**Comment by zachmatson** [comment] 2020-11-19 17:14
My package `ArgMacros.jl` doesn't show the most up-to-date info either, and the latest version was released in September or so.

**Comment by djsegal** [comment] 2021-05-20 20:37
See:

- https://juliapackages.com/packages/featureselectors
- https://juliapackages.com/packages/argmacros

// caused by same issue discussed in #190

**Closed as completed by djsegal** 2021-05-20 20:37 UTC
